version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 81:80
    links:
      - web

  redis:
    command: redis-server --appendonly no --maxmemory-policy allkeys-lru --maxmemory 500mb --loglevel verbose
    restart: always
    image: redis:latest
    hostname: redis.magento2.docker
    ports:
      - 127.0.0.1:6379:6379

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80:80
      - 443:443
    links:
      - magento
      - mysql
    volumes_from:
      - magento
    env_file:
      - ./.env
    #environment:
      #- VIRTUAL_HOST=magento2.docker
      #- VIRTUAL_PORT=80
      #- HTTPS_METHOD=noredirect

  magento:
    hostname: fpm.magento2.docker
    image: meanbee/magento2-php:7.2-fpm
    ports:
      - 8081:80
    links:
      - mysql
      - redis
    volumes:
      - ./magento:/var/www/magento
      - ./volume/.composer:/var/www/.composer
    extra_hosts:
      - "${DOMAIN_NAME}:${LOCAL_HOST_IP}"
    env_file:
      - ./composer.env
      - ./.env
    environment:
      - PHP_APC_ENABLED=1
      - PHP_OPCACHE_ENABLE=1
      - PHP_XDEBUG_ENABLE=0

  mysql:
    image: mariadb:10
    build:
      context: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TERM=meh

  magento_cli:
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.2-cli
    links:
      - mysql
      - redis
    volumes:
      - ./volume/.composer/cache:/root/.composer/cache
    volumes_from:
      - magento
    env_file:
      - ./composer.env
      - ./.env

  magento_cron:
    image: meanbee/magento2-php:7.2-cli
    hostname: magento2-cron.docker
    command: run-cron
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - magento
    links:
      - mysql
      - redis
    env_file:
      - ./composer.env
      - ./.env

  chrome:
    image: selenium/standalone-chrome:3.141.59-titanium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    extra_hosts:
      - "${DOMAIN_NAME}:${LOCAL_HOST_IP}"
